baseURL = 'https://deebakkarthi.com/'
defaultContentLanguage = 'en-us'
defaultContentLanguageInSubdir = false
disableDefaultLanguageRedirect = false
disableLanguages = []
title = 'Deebakkarthi Chinnasame Rani'
theme = 'nostyleplease'

[markup.goldmark.renderHooks.image]
#enableDefault = true
useEmbedded = "fallback"

[markup.goldmark.renderHooks.link]
#enableDefault = true
useEmbedded = "fallback"

[markup]
        [markup.highlight]
                noClasses=false
        [markup.goldmark.renderer]
                unsafe = true

